language: csharp
env: VERSION=0.1.0
solution: KickStart.Net.sln
install:
  - nuget restore KickStart.Net.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:VbcToolExe=vbnc.exe KickStart.Net.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./KickStart.Net.Tests/bin/Release/KickStart.Net.Tests.dll
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - cd KickStart.Net && nuget pack KickStart.Net.nuspec -Version $VERSION.$TRAVIS_BUILD_NUMBER-stable -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      - cd KickStart.Net && nuget pack KickStart.Net.nuspec -Version $TRAVIS_TAG -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
    on:
      tags: true